### ISSUE TITLE
add readme properly

### ISSUE THREAD

**Issue by harshitachaurasia** [harshitachaurasia/assistant#3]

**Comment by pradumio** [comment]
I can work on it. You can assign me. 
Only a questions what needs to be mentioned in readme.md file?

**Comment by Shivamishra21** [comment]
Hey @harshitachaurasia I want to work if i can so will you please brief me details.

**Comment by AdityaPunetha** [comment]
Inform me the content of readme file and i can create it

**Comment by harshitachaurasia** [comment]
@AdityaPunetha , @Shivamishra21 and @pradumio 
It's done already
