### ISSUE TITLE
pyttsx3 module isn't working properly

### ISSUE THREAD

**Issue by harshitachaurasia** [harshitachaurasia/assistant#4]

**Comment by HarshalGoyal** [comment]
Hey @harshitachaurasia what is the main issue with pyttsx3 module ?
i would like to work on it so can you please breif me about the issue please ?

**Comment by jp2373** [comment]
Can you provide more description? (Everything worked fine in my windows pc, just installing all libraries was a mess, you should consider adding a requirement.txt.)

**Comment by BADSHA-36** [comment]
I am getting this issue 
![Screenshot_2020-10-16-15-27-40-37.png](https://user-images.githubusercontent.com/68543287/96246504-58a3c080-0fc6-11eb-98ca-faff9224dd2c.png)
